import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const partsDir = path.join(root, 'src', 'game', 'parts');
const outFile = path.join(root, 'src', 'game.generated.js');

const files = fs.readdirSync(partsDir)
  .filter((name) => name.endsWith('.js'))
  .sort();

if (!files.length) {
  throw new Error(`No game parts found in ${partsDir}`);
}

const body = files
  .map((name) => fs.readFileSync(path.join(partsDir, name), 'utf8').replace(/\s+$/, ''))
  .join('\n\n');

fs.writeFileSync(
  outFile,
  `// AUTO-GENERATED by scripts/assemble-game.mjs.\n// Edit src/game/parts/*.js, then run npm run assemble.\n\n${body}\n`,
  'utf8'
);

console.log(`Assembled ${files.length} files -> ${path.relative(root, outFile)}`);
